services:
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston_api
    restart: unless-stopped
    privileged: true
    ports:
      - "127.0.0.1:2000:2000"
    volumes:
      - ./packages:/piston/packages
    tmpfs:
      - /tmp:exec
